// Login
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";

// Handle change
export const HANDLE_CHANGE_USERNAME = "HANDLE_CHANGE_USERNAME";
export const HANDLE_CHANGE_PASSWORD = "HANDLE_CHANGE_PASSWORD";
export const HANDLE_CHANGE_PHONE = "HANDLE_CHANGE_PHONE";
export const HANDLE_CHANGE_SMS = "HANDLE_CHANGE_SMS";

// associate require update
export const ASSOCIATE_REQUIRED = "ASSOCIATE_REQUIRED";

// phone number
export const PHONE_NUMBER_SUCCESS = "PHONE_NUMBER_SUCCESS";
export const CHALLENGE_SUCCESS = "CHALLENGE_SUCCESS";
export const PHONE_NUMBER_ERROR = "PHONE_NUMBER_ERROR";
export const PHONE_NUMBER_REQUEST = "PHONE_NUMBER_REQUEST";

// sms injection
export const SMS_CODE_SUCCESS = "SMS_CODE_SUCCESS";
export const SMS_CODE_ERROR = "SMS_CODE_ERROR";
export const SMS_CODE_REQUEST = "SMS_CODE_REQUEST";
