export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";

export const HANDLE_CHANGE_USERNAME = "HANDLE_CHANGE_USERNAME";
export const HANDLE_CHANGE_PASSWORD = "HANDLE_CHANGE_PASSWORD";
